### ISSUE TITLE
Prove that Kafka is suitable as a centralized event log system

### ISSUE THREAD

**Issue by beevee** [vostok/core#3]
Current requirements:

- 1 million events per second on regular server hardware (~10 servers)
- 1 week storage time without loss of performance

Work plan:

- [x] Show reproducible results with a single Java gate/producer with clear bottlenecks
- [x] Write a Java consumer application
- [x] Show reproducible results with full cycle Java producer/kafka/consumer with clear bottlenecks
- [x] Show reproducible results with a single C# gate/producer with clear bottlenecks
- [x] Research time-based indices API
- [x] Add Kafka-specific metrics to dashboards

**Comment by beevee** [comment]
Current hardware setup:

3×Kafka:
2×CPU E5-2620 0 @ 2.00GHz 6 Cores
128GB RAM
1TB RAID6 (?) HDD
1Gb network

1×Airlock prototype (https://github.com/AndrewKostousov/kload):
2×CPU E5-2609 v4 @ 1.70GHz 8 Cores
64GB RAM
1×480GB SSD + 3×4TB HDD
1Gb network

**Comment by beevee** [comment]
https://overload.yandex.net/25773
https://overload.yandex.net/25774
https://overload.yandex.net/25776

**Comment by beevee** [comment]
Текущие пределы производительности для C#-версии:

/ping:
https://overload.yandex.net/26027

**Comment by iloktionov** [comment]
Я посмотрел по диагонали на код дотнетовского бенчмарк-сервера, и он совсем не выдерживает критики. Для начала надо сделать две вещи:
1. Прочесть [статью](https://staff.skbkontur.ru/?m=article-59895ab9339efc1f102c124a) и применить на практике хотя бы первый пункт.
2. Выкинуть owin и сделать на чистом kestrel'е.

**Comment by AndrewKostousov** [comment]
Прогнал тесты с одним консьюмером, запущенном на той же машине, что и шлюз (edi18). Метрика TravelTime (TT) - это время между моментом генерации события на шлюзе и моментом, когда это событие становится доступно обработчику в консьюмере.

/kload10:
https://overload.yandex.net/35055 (8000 RPS, TT < 10ms,  OK)

/kload100:
https://overload.yandex.net/35060 (5000 RPS, TT < 10ms,  OK)

**Comment by AndrewKostousov** [comment]
Прогнал тесты с тремя продьюсерами и тремя консьюмерами, запущенными на одних и тех же машинах edi18, icat-test04, icat-test05. Танк стрелял по трем мишеням параллельно с одной скоростью. Каждый консьюмер вычитывал все ивенты в три потока (по одному потоку на партишен). Метрика MeanTravelTime (MTT) - это время между моментом генерации события на шлюзе и моментом, когда это событие становится доступно обработчику в консьюмере, усредненное за 3 секунды.

/kload100 (один запрос на шлюз генерирует 100 ивентов размером по 100 байт каждый):
https://overload.yandex.net/39532 (3x2000 RPS в течение 10 минут, MTT < 20 ms, OK)
https://overload.yandex.net/39467 (3x2500 RPS в течение 5 минут, FAIL) - здесь консьюмеры не успевали в режиме реального времени все ивенты вычитывать (см. метрику mean-travel-time)ъ

/kload1000 (ивенты размером по 1KB):
https://overload.yandex.net/39552 (3x200 RPS в течение 5 минут, MTT < 20 ms, OK)
https://overload.yandex.net/39543 (3x1000 RPS в течение 2 минут, FAIL) - уперлись в сеть на стороне консьюмера

**Comment by trurl123** [comment]
Итоги тестирования клиента кафки на .net
Общее
- На линуксе всё работает медленнее, чем на винде примерно в 2 раза, иногда и на порядок медленнее
- Получение сообщений в общем случае медленнее, чем отправка.
- Единственная нормальная библиотека на .Net - это обертка над библиотекой librdkafka.
- Многопоточная работа не дает прироста производительности (несколько получателей или несколько потоков отправки)
- В основном тестировал сообщения по 10 байт
- Использовал многомерную оптимизацию по параметрам, что дало существенное ускорение работы
- На линуксе еще не до конца протестировал многомерную оптимизацию
Отправка
- Библиотека librdkafka на windows может отправлять около 1 млн сообщений в сек.
- Обертка на .net над librdkafka отправляет около 1млн сообщений в сек, без оптимизации 800 тыс сообщений в сек
Получение
- Напрямую librdkafka не стал использовать, поскольку необходимо писать слишком много кода
- Обертка на .net над librdkafka получает около 1млн сообщений в сек, без оптимизации около 500 тыс сообщений в сек

**Comment by trurl123** [comment]
При тестировании веб-сервиса .net по аналогии с Java для отправки сообщений, наблюдается замедление отправки примерно на 30%

**Comment by trurl123** [comment]
Для .net по линуксу максильный RPS на отправку на edi18 удалось сделать 118358
на получение максимальный RPS 488671 на icat-test04

**Comment by trurl123** [comment]
на icat-test04 средний RPS 200 тыс

**Comment by trurl123** [comment]
Решил провести тест java более приближенный к реальности - отправлять в одном запросе не множество задач в кафку, а одну большую задачу 
Получилось 136 Mb/sec и 15 тыс RPS
https://overload.yandex.net/41379

Аналогичный тест на c#
асинхронный вызов https://overload.yandex.net/41380
синхронный https://overload.yandex.net/41381
В последнем тесте кол-во событий в сек нужно умножать на 100, чтобы привести в соотв. к предыдущим тестам

в итоге c# на порядок хуже

**Comment by trurl123** [comment]
Протестировали отправку по 10Kb на java, c# на windows и linux веб сервисом в кафку. На каждый http-запрос отправляли одно сообщение в кафку.
Java: https://overload.yandex.net/41379
C# linux: https://overload.yandex.net/41854
C# windows: https://overload.yandex.net/online/41859
На windows на закладке мониторинга не видно статистики на клиенте кафки, поскольку танк не смог установить своего агента туда по понятным причинам.
На таких тестах объем данных в секунду одного порядка: 100 Mb/sec.
На java побыстрее: 125 Mb/sec.
На c# Linux: 103 Mb/sec
На windows тоже около 100Mb/sec, но скорость сильно скачет

Если тестировать как раньше, на каждый http-запрос отправлять по 100 запросов в кафку, то c# существенно проигрывает java, примерно на порядок.

**Comment by trurl123** [comment]
Прогнал через танк гейт, который принимает данные и пересылает их в кафку. 
Объем данных вычислялся через объем http-реквеста, кол-во событий вычислялось через кол-во событий в кафке. Если событие 10 байт, то сами данные, отправляемые в кафку занимали примерно половину реквеста. На 100 и 1000 байт не такие сильные различия.
Результаты:
Событие 10 байт https://overload.yandex.net/45808
Событие 100 байт https://overload.yandex.net/45812
Событие 1000 байт https://overload.yandex.net/45814
Результаты получились лучше, чем в мегатесте Андрея Костоусова. Возможно из-за того, что не использовалась Avro-сериализация, ну и это был не мегатест, а тест одного продьюсера.
